    services:

      # Oracle service (label used to access the service container)
      oracle:

        # Docker Hub image (feel free to change the tag "latest" to any other available one)
        image: gvenzl/oracle-xe:latest

        # Provide passwords and other environment variables to container
        environment:
          ORACLE_RANDOM_PASSWORD: true
          APP_USER: mat
          APP_USER_PASSWORD: isanizard

        # Forward Oracle port
        ports:
          - 1521:1521

        expose:
          - "1521"
        # Provide healthcheck script options for startup
        #options: >-
         # --health-cmd healthcheck.sh
         # --health-interval 10s
          #--health-timeout 5s
          #--health-retries 10
